### ISSUE TITLE
Render Deployment Error

### ISSUE THREAD

**Issue by Tosyyyaaa** [marwonn/marcify#12]
Hi there! I have followed the steps you’ve written on how to deploy an app, however an error occurred as the Build Command has failed (you didn’t mention it, so I didn’t make any changes). I am working on my CS school coursework and I am working on coding a music recommendation system, could you please help me with the issue I faced? Thank you very much!

**Comment by marwonn** [comment]
Hi there! Sorry for my late reply. Currently, I focus on other projects and I am not maintaining this project. Maybe something changed on the Render side. What does the logs show exactly?
